services:
  sunrise-build-deck:
    platform: linux/amd64

    build:
      context: .

    volumes:
      - ./:/app

    working_dir: /app

    stdin_open: true
    tty: true

    environment:
      - npm_config_cache=/tmp/npm-cache

    command: /bin/bash